import { Badge } from '@/components/ui/badge';
import { Database, Sparkles, Plug } from 'lucide-react';
import { cn } from '@/lib/utils';

export type DataSourceType = 'real_api' | 'first_party' | 'ai_estimated';

const CONFIG: Record<
  DataSourceType,
  { label: string; title: string; icon: typeof Database; className: string }
> = {
  real_api: {
    label: 'Live Platform Data',
    title: 'Pulled directly from the ad platform API.',
    icon: Plug,
    className: 'border-emerald-500/40 text-emerald-500 bg-emerald-500/10',
  },
  first_party: {
    label: 'Your Data',
    title: 'Measured from your own published posts and analytics — our most trustworthy source.',
    icon: Database,
    className: 'border-primary/50 text-primary bg-primary/10',
  },
  ai_estimated: {
    label: 'AI-Estimated',
    title:
      'Generated by an AI model from prior knowledge — not live platform data. Treat as a directional estimate.',
    icon: Sparkles,
    className: 'border-amber-500/50 text-amber-500 bg-amber-500/10',
  },
};

export function DataSourceBadge({
  type,
  className,
  showLabel = true,
}: {
  type: DataSourceType;
  className?: string;
  showLabel?: boolean;
}) {
  const cfg = CONFIG[type] ?? CONFIG.ai_estimated;
  const Icon = cfg.icon;
  return (
    <Badge
      variant="outline"
      title={cfg.title}
      className={cn('gap-1 font-medium shrink-0', cfg.className, className)}
    >
      <Icon className="w-3 h-3" aria-hidden="true" />
      {showLabel && cfg.label}
    </Badge>
  );
}

export function dataSourceLabel(type: DataSourceType) {
  return (CONFIG[type] ?? CONFIG.ai_estimated).label;
}
